---
name: build and test
on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run ESLint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    name: Run TypeScript typechecker
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run tsc
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    name: Build userscripts
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Compile userscripts
        run: npm run build

  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run jest
        run: npm run test
      - name: Upload coverage data
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info

  e2e-test:
    runs-on: ubuntu-latest
    name: Run E2E tests
    strategy:
      matrix:
        browserProfile:
          - chrome:latest
          # Although MB supports Chrome 49 and above (and we do too), the
          # latest VM and TM versions only support Chrome 64 and up.
          - chrome:64.0
          - firefox:latest
          - firefox:52.0
        userscriptManager:
          - violentmonkey
    steps:
      - name: Pull Selenoid images
        run: |
          docker pull selenoid/${{ matrix.browserProfile }}
          docker pull selenoid/video-recorder:latest-release
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Start E2E services
        run: docker-compose -f tests/e2e/docker/docker-compose.yml up -d
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run codeceptjs
        run: npm run test:e2e -- --profile ${{ matrix.browserProfile }}/${{ matrix.userscriptManager }}
