---
name: build and test
on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run ESLint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    name: Run TypeScript typechecker
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run tsc
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    name: Build userscripts
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Compile userscripts
        run: npm run build

  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run jest
        run: npm run test

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage/lcov.info
          retention-days: 7

  upload-coverage:
    needs: [test]
    runs-on: ubuntu-latest
    name: Upload coverage data
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Upload coverage data
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
