---
name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and test
    uses: ROpdebee/mb-userscripts/.github/workflows/build-and-test.yml@main

  codeql:
    name: CodeQL analysis
    uses: ROpdebee/mb-userscripts/.github/workflows/codeql-analysis.yml@main

  deploy:
    needs: build-and-test
    if: always() && github.repository == 'ROpdebee/mb-userscripts'
    uses: ROpdebee/mb-userscripts/.github/workflows/deploy.yml@cd-preview-on-pr
    with:
      test-result: ${{ needs.build-and-test.result }}
      preview: ${{ github.event_name == 'pull_request' }}
