---
name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and test
    uses: ROpdebee/mb-userscripts/.github/workflows/build-and-test.yml@main

  codeql:
    name: CodeQL analysis
    uses: ROpdebee/mb-userscripts/.github/workflows/codeql-analysis.yml@main

  deploy:
    needs: build-and-test
    if: >
      always()
      && github.event_name == 'push'
      && github.event.ref == 'refs/heads/main'
      && github.repository == 'ROpdebee/mb-userscripts'
    uses: ROpdebee/mb-userscripts/.github/workflows/deploy.yml@main
    with:
      test-result: ${{ needs.build-and-test.result }}

  deploy-check:
    needs: build-and-test
    if: >
      github.event_name == 'pull_request'
      && github.repository == 'ROpdebee/mb-userscripts'
    uses: ROpdebee/mb-userscripts/.github/workflows/deploy-check.yml@main
