---
name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # Periodically run CI for CodeQL security advisories etc, in case new checks
  # are added.
  schedule:
    - cron: "39 12 * * 0"

jobs:
  build-and-test:
    name: Build and test
    if: "!startsWith(github.head_ref, 'renovate/')" # Already covered by renovate-check.
    uses: ROpdebee/mb-userscripts/.github/workflows/build-and-test.yml@main

  codeql:
    name: CodeQL analysis
    uses: ROpdebee/mb-userscripts/.github/workflows/codeql-analysis.yml@main

  deploy:
    needs: build-and-test
    if: >
      always()
      && github.event_name == 'push'
      && github.event.ref == 'refs/heads/main'
      && github.repository == 'ROpdebee/mb-userscripts'
    uses: ROpdebee/mb-userscripts/.github/workflows/deploy.yml@main
    with:
      test-result: ${{ needs.build-and-test.result }}
