---
name: deploy
on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  # Make sure we can build and that tests pass before deploying
  buildAndTest:
    name: Build and test
    if: >
      github.event.pull_request.merged
      && github.repository == 'ROpdebee/mb-userscripts'
      && !contains(github.event.pull_request.labels.*.name, 'skip cd')
    uses: ROpdebee/mb-userscripts/.github/workflows/main.yml@main
    with:
      codecov_override_branch: main

  deploy:
    # If buildAndTest is skipped, this will be too.
    needs: [buildAndTest]
    runs-on: ubuntu-latest
    name: Deploy userscripts
    outputs:
      deployMessage: ${{ steps.deployStep.outputs.deployMessage }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Checkout second dist copy
        uses: actions/checkout@v2
        with:
          path: repoDist
          ref: dist
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install project dependencies
        run: npm ci
      - name: Deploy new userscript versions
        id: deployStep
        env:
          PR_TITLE: ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})
        run: |
          cd repoDist
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name 'GitHub Actions'
          cd -
          npm run deploy repoDist "$PR_TITLE"

  report:
    name: 'Report deployment status'
    if: >
      always()
      && needs.deploy.result != 'skipped'
      && needs.deploy.result != 'cancelled'
    runs-on: ubuntu-latest
    needs: [buildAndTest, deploy]
    steps:
      - name: Warn if deployment is skipped due to test failures
        if: needs.buildAndTest.result != 'success'
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Heads up! Automatic deployment of the changes in this PR failed due to a build or test failure.'
            })
      - name: Warn if deployment is skipped due to deployment failures
        if: needs.deploy.result != 'success'
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Heads up! Automatic deployment of the changes in this PR failed for unknown reason!'
            })
      - name: Report which versions have been deployed.
        if: needs.deploy.result == 'success'
        uses: actions/github-script@v5
        env:
          COMMENT_CONTENT: ${{ needs.deploy.outputs.deployMessage || 'This PR made no changes to the built userscripts. No new userscript versions deployed.' }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.COMMENT_CONTENT,
            })
