---
name: deploy-check
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Check and report whether deploy will be necessary
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Find out PR number and title
        id: active-pr
        uses: actions/github-script@v5
        with:
          script: |
            // This is a PR. We can easily find the number, title, and labels
            // through the event payload
            const pr = context.payload.pull_request;
            return {
              number: pr.number,
              title: pr.title,
              labels: pr.labels.map((label) => label.name),
            };

      - name: Checkout second dist copy
        uses: actions/checkout@v2
        with:
          path: repoDist
          ref: dist

      - name: Dry-run deploying new userscript versions
        id: deploy-step
        env:
          PR_INFO: ${{ steps.active-pr.outputs.result }}
          # Since this is running from a pull_request event, PRs from forks
          # won't have the appropriate access level to create pushes anyway.
          SKIP_PUSH: 1
        run: npm run deploy repoDist

      - name: Report preview
        # Will be skipped if deployment failed
        env:
          PR_INFO: ${{ steps.active-pr.outputs.result }}
          DEPLOY_INFO: ${{ steps.deploy-step.outputs.deployment-info }}
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./build/report-deploy.js');
            await script.reportPreview({ github, context, full: false });
