---
name: Check renovate auto-merge applicability
on:
  push:
    branches:
      - renovate/*

jobs:
  build-and-test:
    name: Build and test
    uses: ROpdebee/mb-userscripts/.github/workflows/build-and-test.yml@main

  fail-changed-userscript:
    name: Fail if userscripts are changed by update
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # Fetch the whole repository history, as we need to check out an old
          # ref to compare compiled scripts from before and after the change.
          fetch-depth: 0
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Checkout second dist copy
        uses: actions/checkout@v3
        with:
          path: repoDist
          ref: dist

      - name: Check that userscripts remain unchanged
        env:
          NODE_ENV: production  # Necessary to ensure we minify in the preview
        run: npx ts-node -r tsconfig-paths/register build/check-scripts-unchanged.ts repoDist
